# Generated by Django 3.2 on 2021-04-18 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contingent', '0003_studenthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('data_name', models.CharField(max_length=200)),
                ('model_name', models.CharField(blank=True, max_length=50, null=True)),
                ('is_history', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ReportField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('filter_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contingent.filterfield')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contingent.report')),
            ],
        ),
    ]
