# Generated by Django 3.2 on 2021-04-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contingent', '0004_filterfield_report_reportfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
